### ISSUE TITLE
Laravel Echo Serve in docker exited with code 0

### ISSUE THREAD

**Issue by lokingwei** [tlaverdure/laravel-echo-server#412]
I used laradock setting to create laravel-echo-server container which running in VM.
Whenever I shutdown the VM ungracefully (a.k.a force shut down), I unable to start back the server within the same container.

Unfortunately, there's no log or error code for me to indicate what is happening.

The only output I have is:
```
Starting laradock_laravel-echo-server_1_e1682066e464 ... done
Attaching to laradock_laravel-echo-server_1_e1682066e464
laravel-echo-server_1_e1682066e464 |
laravel-echo-server_1_e1682066e464 | > laravel-echo-server-docker@0.0.1 start /usr/src/app
laravel-echo-server_1_e1682066e464 | > laravel-echo-server start "--force"
laravel-echo-server_1_e1682066e464 |
laradock_laravel-echo-server_1_e1682066e464 exited with code 0
```

My Dockerfile:
```
FROM node:alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install

# Bundle app source
COPY laravel-echo-server.json /usr/src/app/laravel-echo-server.json

EXPOSE 3000
CMD [ "npm", "start", "--", "--force"]
```

My package.json
```
{
  "name": "laravel-echo-server-docker",
  "description": "Docker container for running laravel-echo-server",
  "version": "0.0.1",
  "license": "MIT",
  "dependencies": {
    "laravel-echo-server": "1.5"
  },
  "scripts": {
    "start": "laravel-echo-server start"
  }
}
```

My laravel-echo-server.json
```
{
	"authHost": "php-fpm",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "redis"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": ""
}
```

My docker-compose.yml:
```
laravel-echo-server:
      build:
        context: ./laravel-echo-server
      volumes:
        - ./laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json
      ports:
        - "${LARAVEL_ECHO_SERVER_PORT}:6001"
      depends_on:
        - redis
      networks:
        - frontend
        - backend
```
