### ISSUE TITLE
POST /socket.io/* return "Cannot POST /"

### ISSUE THREAD

**Issue by silasrm** [tlaverdure/laravel-echo-server#517]
**Describe the bug**
I'm using nginx to proxying my /socket.io/ to other docker container, but GET /socket.io/ return OK and in sequence has a POST /socket.io/ returning "Cannot POST /".

I've 3 containers: nginx, app (laravel) and echo.

**To Reproduce**
My configurations:
- __nginx vhost in separated container__:
```
server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    client_body_buffer_size     100M;
    client_max_body_size        100M;

    error_log /var/www/storage/logs/nginx-error.log error;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    #if (!-e $request_filename) {
    #    rewrite ^.*$ /index.php last;
    #}

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /socket.io/ {
        proxy_pass http://echo:6001/; #could be localhost if Echo and NginX are on the same box
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;
        fastcgi_read_timeout 600;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

- __bootstrap.js from my app__:
```
import Echo from 'laravel-echo'
import io from 'socket.io-client'

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.host,
    client: io
});
```

- __requests__:
URL: GET http://localhost:8009/socket.io/?EIO=3&transport=polling&t=N7SiCj2
Return: status 200 OK

URL: POST http://localhost:8009/socket.io/?EIO=3&transport=polling&t=N7SiClo
Return: status 404
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /</pre>
</body>
</html>
```

**Expected behavior**
I don't know.

**Comment by nicolashuber** [comment]
How is your `laravel-echo-server.json`?

**Comment by silasrm** [comment]
My echo config:

```
{
	"apiOriginAllow": {
        "allowCors": false,
        "allowOrigin": "*",
        "allowMethods": "GET, POST",
        "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
    },
	"authEndpoint": "/broadcasting/auth",
	"authHost": "http://nginx
	"clients": [
		{
			"appId": "myapp",
			"key": "generated key for myapp"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"host": "redis",
			"port": "6379",
			"keyPrefix": "myapp_database_",
			"options": {
				"db": "0"
			}
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		},
		"publishPresence": true
	},
	"devMode": true,
	"host": null,
	"port": 6001,
	"protocol": "http",
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"socketio": {},
	"subscribers": {
		"http": true,
		"redis": true
	}
}
```

**Comment by silasrm** [comment]
My problem is solved. See my configs:
__docker-compose.yml:__
```
version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    restart: always
    tty: true
    ports:
      - "8009:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app
      - echo

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33009:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  echo:
    build: .docker/echo
    container_name: echo
    restart: always
    tty: true
    ports:
      - "60001:6001"
    volumes:
      - ./.docker/echo:/app
    depends_on:
      - redis
      - app
    networks:
      - app-network

  redis:
    build: .docker/redis
    container_name: redis
    ports:
      - "60379:6379"
    volumes:
      - ./.docker/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
```

__redis/Dockerfile:__
```
FROM redis:6.0.1-alpine
CMD [ "redis-server" ]
```

__nginx/Dockerfile:__```

FROM nginx:1.17.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d
```

__nginx/nginx.conf:__
```
server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    client_body_buffer_size     100M;
    client_max_body_size        100M;
    sendfile                    on;
    keepalive_timeout           3;
    gzip                        on;

    error_log /var/www/storage/logs/nginx-error.log error;

    charset utf-8;

    location /socket.io {
        proxy_pass http://echo:6001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files       $fastcgi_script_name =404;
        fastcgi_pass    app:9000;
        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index   index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;
        fastcgi_read_timeout 600;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        log_not_found off;
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        expires off;
    }

    location ~ /\.ht {
        deny  all;
    }
}
```

__echo/laravel-echo-server.json:__
```
{
	"apiOriginAllow": {
        "allowCors": true,
        "allowOrigin": "*",
        "allowMethods": "GET, POST",
        "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
    },
	"authEndpoint": "/broadcasting/auth",
	"authHost": "http://nginx",
	"clients": [
		{
			"appId": "myapp",
			"key": "key_generated"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"host": "redis",
			"port": "6379",
			"keyPrefix": "",
			"options": {
				"db": "0"
			}
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		},
		"publishPresence": true
	},
	"devMode": true,
	"host": null,
	"port": 6001,
	"protocol": "http",
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"socketio": {},
	"subscribers": {
		"http": true,
		"redis": true
	}
}
```

__.env:__
```
BROADCAST_DRIVER=pusher
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_CLIENT=predis
REDIS_PREFIX=""

PUSHER_APP_ID=myapp
PUSHER_APP_KEY=key_generated
PUSHER_APP_SECRET=null
PUSHER_APP_CLUSTER=mt1
ECHO_HOST=echo
ECHO_PORT=6001
ECHO_SCHEME=http

MIX_ECHO_HOST="${APP_URL}"
```

__config/broadcast.php:__
```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'host' => env('ECHO_HOST', 'localhost'),
                'port' => env('ECHO_PORT', 6001),
                'scheme' => env('ECHO_SCHEME', 'http')
            ],
        ],
```

Running queue:
```php artisan queue:work --tries=3```
